kafkaCluster:
  app_id: noceStream0106
  brokers: XTH04-Sugoni840-8:9091,XTH04-Sugoni840-8:9092,XTH04-Sugoni840-9:9093,XTH04-Sugoni840-9:9094,XTH04-Sugoni840-10:9095,XTH04-Sugoni840-10:9096,XTH04-Sugoni840-11:9097,XTH04-Sugoni840-11:9098,XTH04-Sugoni840-12:9099,XTH04-Sugoni840-12:9091
  client_id: noce
  zookeeper: XTH04-Sugoni840-10:2182,XTH04-Sugoni840-11:2182,XTH04-Sugoni840-12:2182/kafkaCluster
  topic: 4GDPI
  auto_offset_reset: latest
  timestamp_extractor: org.apache.kafka.streams.processor.WallclockTimestampExtractor

bloomFilter:
  filter: true
  falsePositiveProbability: 0.1
  expectedSize: 1000000
  name:
      - 5min-bloomFilter
      - 1hour-bloomFilter
      - 1day-bloomFilter
    
sourceFields:
  fields: 
      - MSISDN
      - ECGI
      - SGWIP
      - InputOctets
      - OutputOctets
      - Domain
      - TimeStamp
  delimiter: \|

couterList:
  - huawei4g-userstat-5min
  - huawei4g-userstat-1hour
  - huawei4g-userstat-1day
  - userstat-mdnprefix-5min
  - userstat-mdnprefix-1hour
  - userstat-mdnprefix-1day
  - userstat-shortmdnprefix-5min
  - userstat-shortmdnprefix-1hour
  - userstat-shortmdnprefix-1day
  - userstat-CGI-5min
  - mdn-prefix-data-1hour
  - short-mdn-prefix-data-1hour
  - dpi-1hour
  - mdn-day-data
  - domain-5min
 # - CGI-5min 
  - CGI-data-5min
  - CGI-domain-5min
  
#derepeated mdn and mdn-prefix stat in 5 min
huawei4g-userstat-5min:
  type: com.gsta.bigdata.stream.UserStatCounter
  flushes: elasticsearch
  flushTimeGapRatio: 2.0
  bloomFilter: 5min-bloomFilter
  timeGap: 5min
    
#derepeated mdn and mdn-prefix stat in 1 hour   
huawei4g-userstat-1hour:
  type: com.gsta.bigdata.stream.UserStatCounter
  flushes: elasticsearch
  flushTimeGapRatio: 1.1
  bloomFilter: 1hour-bloomFilter
  timeGap: 1hour

#derepeated mdn and mdn-prefix stat in 1 day
huawei4g-userstat-1day:
  type: com.gsta.bigdata.stream.UserStatCounter
  flushes: elasticsearch
  flushTimeGapRatio: 1.02
  bloomFilter: 1day-bloomFilter
  timeGap: 1day

userstat-mdnprefix-5min:
  type: com.gsta.bigdata.stream.MDNPrefixCounter
  flushes: elasticsearch
  flushTimeGapRatio: 2.0
  bloomFilter: 5min-bloomFilter
  keyFields: mdnprefix  
  timeGap: 5min
    
userstat-mdnprefix-1hour:
  type: com.gsta.bigdata.stream.MDNPrefixCounter
  flushes: elasticsearch
  flushTimeGapRatio: 1.1
  bloomFilter: 1hour-bloomFilter
  keyFields: mdnprefix  
  timeGap: 1hour

userstat-mdnprefix-1day:
  type: com.gsta.bigdata.stream.MDNPrefixCounter
  flushes: elasticsearch
  flushTimeGapRatio: 1.02
  bloomFilter: 1day-bloomFilter
  keyFields: mdnprefix  
  timeGap: 1day

userstat-shortmdnprefix-5min:
  type: com.gsta.bigdata.stream.MDNPrefixCounter
  flushes: elasticsearch
  flushTimeGapRatio: 2.0
  bloomFilter: 5min-bloomFilter
  keyFields: mdnprefix
  shortmdnprefix: true  
  timeGap: 5min
    
userstat-shortmdnprefix-1hour:
  type: com.gsta.bigdata.stream.MDNPrefixCounter
  flushes: elasticsearch
  flushTimeGapRatio: 1.1
  bloomFilter: 1hour-bloomFilter
  keyFields: mdnprefix  
  shortmdnprefix: true 
  timeGap: 1hour

userstat-shortmdnprefix-1day:
  type: com.gsta.bigdata.stream.MDNPrefixCounter
  flushes: elasticsearch
  flushTimeGapRatio: 1.02
  bloomFilter: 1day-bloomFilter
  keyFields: mdnprefix  
  shortmdnprefix: true 
  timeGap: 1day
  
userstat-CGI-5min:
  type: com.gsta.bigdata.stream.CGIUser5MinCounter
  flushes: elasticsearch
  flushTimeGapRatio: 2.0
  bloomFilter: 5min-bloomFilter
  keyFields: ECGI

#mdn prefix data count in 1 hour
mdn-prefix-data-1hour:
  type: com.gsta.bigdata.stream.MDNPrefix1HourDataCounter
  flushes: elasticsearch
  flushTimeGapRatio: 1.1
  keyFields: mdnprefix
  
short-mdn-prefix-data-1hour:
  type: com.gsta.bigdata.stream.MDNPrefix1HourDataCounter
  flushes: elasticsearch
  flushTimeGapRatio: 1.1
  keyFields: mdnprefix
  shortmdnprefix: true  
    
#dpi count in 1 hour
dpi-1hour:
  type: com.gsta.bigdata.stream.DPI1HourCounter
  flushes: elasticsearch
  flushTimeGapRatio: 1.1
  
mdn-day-data:
  type: com.gsta.bigdata.stream.MDNDayDataCounter
  flushes: elasticsearch
  flushTimeGapRatio: 1.02
  continuousFlushes: mdnDayRedis
  #unit is second
  flushWaitTime: 120
  keyFields: MSISDN

domain-5min:
  type: com.gsta.bigdata.stream.Field5MinCounter
  flushes: elasticsearch
  flushTimeGapRatio: 1.1
  keyFields: Domain

CGI-5min:
  type: com.gsta.bigdata.stream.Field5MinCounter
  flushes: elasticsearch
  flushTimeGapRatio: 1.1
  keyFields: ECGI 

CGI-data-5min:
  type: com.gsta.bigdata.stream.CGIData5MinCounter
  flushes: elasticsearch
  flushTimeGapRatio: 1.1
  keyFields: ECGI

CGI-domain-5min:
  type: com.gsta.bigdata.stream.MultiField5MinCounter
  flushes: elasticsearch
  flushTimeGapRatio: 1.1
  keyFields: ECGI,Domain
    
redis:
  host: XTH04-Sugoni840-9
  port: 6379
  #unit is second,604800 second = 7day
  keyExpire: 604800 
  maxTotal: 200
  maxIdle: 200
  minIdle: 8
  numTestsPerEvictionRun: 10
  timeBetweenEvictionRunsMillis: 30000
  minEvictableIdleTimeMillis: -1
  softMinEvictableIdleTimeMillis: 10000
  maxWaitMillis: 10000
  testOnBorrow: true
  testWhileIdle: true
  testOnReturn: true
  blockWhenExhausted: false

elasticsearch:
  cluster.name: gd
  client.transport.sniff: true
  cluster.nodes:
      - XTH04-Sugoni840-8
      - XTH04-Sugoni840-9
      - XTH04-Sugoni840-10
  port: 9300
  index.name: 4gdpi