kafkaCluster:
    app_id: noceStream1214
    brokers: 132.122.70.131:9091,132.122.70.131:9092,132.122.70.132:9093,132.122.70.132:9094,132.122.70.133:9095,132.122.70.133:9096,132.122.70.134:9097,132.122.70.134:9098,132.122.70.135:9099,132.122.70.135:9091
    client_id: noce
    zookeeper: 132.122.70.140:2181,132.122.70.141:2181,132.122.70.142:2181/kafkaCluster
    topic: 4GDPI
    auto_offset_reset: latest
    timestamp_extractor: org.apache.kafka.streams.processor.WallclockTimestampExtractor

sourceFields:
    fields: 
        - MSISDN
        - ECGI
        - SGWIP
        - InputOctets
        - OutputOctets
        - Domain
        - TimeStamp
    delimiter: \|

couterList:
    - huawei4g-userstat-5min
    - huawei4g-userstat-1hour
    - huawei4g-userstat-1day
    - mdn-prefix-data-1hour
    - dpi-1hour
    - mdn-day-data
    - domain-5min
    - CGI-5min 
  
#derepeated mdn and mdn-prefix stat in 5 min
huawei4g-userstat-5min:
    type: com.gsta.bigdata.stream.DPIUserStatCounter
    flushes: elasticsearch
    flushTimeGapRatio: 2.0
    
#derepeated mdn and mdn-prefix stat in 1 hour   
huawei4g-userstat-1hour:
    type: com.gsta.bigdata.stream.DPIUserStatCounter
    flushes: elasticsearch
    flushTimeGapRatio: 1.1

#derepeated mdn and mdn-prefix stat in 1 day
huawei4g-userstat-1day:
    type: com.gsta.bigdata.stream.DPIUserStatCounter
    flushes: elasticsearch
    flushTimeGapRatio: 1.02

#mdn prefix data count in 1 hour
mdn-prefix-data-1hour:
    type: com.gsta.bigdata.stream.MDNPrefix1HourDataCounter
    flushes: elasticsearch
    flushTimeGapRatio: 1.1
    
#dpi count in 1 hour
dpi-1hour:
    type: com.gsta.bigdata.stream.DPI1HourCounter
    flushes: elasticsearch
    flushTimeGapRatio: 1.1
  
mdn-day-data:
    type: com.gsta.bigdata.stream.MDNDayDataCounter
    flushes: elasticsearch
    flushTimeGapRatio: 1.02
    continuousFlushes: mdnDayRedis
    #unit is second
    flushWaitTime: 120

domain-5min:
    type: com.gsta.bigdata.stream.Field5MinCounter
    flushes: elasticsearch
    flushTimeGapRatio: 1.1
    statField: Domain

CGI-5min:
    type: com.gsta.bigdata.stream.Field5MinCounter
    flushes: elasticsearch
    flushTimeGapRatio: 1.1
    statField: ECGI 
    
mysql:
    url: jdbc:mysql://132.122.70.138:3306/streamstat?useUnicode=true&characterEncoding=UTF-8
    user: root
    pwd: horuseye
    initialPoolSize: 10
    minPoolSize: 5
    maxPoolSize: 20
    testConnectionOnCheckin: true
    automaticTestTable: c3p0TestTable
    idleConnectionTestPeriod: 300
    maxIdleTime: 1800
    checkoutTimeout: 3000
  
opentsdb:
    url: http://132.122.70.138:4242
    
redis:
    host: 132.122.70.132
    port: 6379
    #unit is second,604800 second = 7day
    keyExpire: 604800 
    maxTotal: 200
    maxIdle: 200
    minIdle: 8
    numTestsPerEvictionRun: 10
    timeBetweenEvictionRunsMillis: 30000
    minEvictableIdleTimeMillis: -1
    softMinEvictableIdleTimeMillis: 10000
    maxWaitMillis: 10000
    testOnBorrow: true
    testWhileIdle: true
    testOnReturn: true
    blockWhenExhausted: false

elasticsearch:
    cluster.name: gd
    client.transport.sniff: true
    cluster.nodes:
        - 132.122.70.131
        - 132.122.70.132
        - 132.122.70.133
    port: 9300
    index.name: 4gdpi

bloomFilter:
    falsePositiveProbability: 0.1
    expectedSize: 1000000