kafkaCluster:
  #stream config
#  application.id: noceStream20170312-1
  bootstrap.servers: XTH04-Sugoni840-8:9091,XTH04-Sugoni840-8:9092,XTH04-Sugoni840-9:9093,XTH04-Sugoni840-9:9094,XTH04-Sugoni840-10:9095,XTH04-Sugoni840-10:9096,XTH04-Sugoni840-11:9097,XTH04-Sugoni840-11:9098,XTH04-Sugoni840-12:9099,XTH04-Sugoni840-12:9091
  client.id: noce
  zookeeper.connect: XTH04-Sugoni840-10:2182,XTH04-Sugoni840-11:2182,XTH04-Sugoni840-12:2182/kafkaCluster
  inputTopic: 4GDPI
  defaultOutputTopic: tempMain
  timestamp.extractor: org.apache.kafka.streams.processor.WallclockTimestampExtractor
  state.dir: STATE_DIR
  buffered.records.per.partition: 2000
  num.stream.threads: 1
  poll.ms: 100
  cache.max.bytes.buffering: 10485760
  commit.interval.ms: 30000
  #consumer config
  auto.offset.reset: latest
  max.partition.fetch.bytes: 2097152
  max.poll.records: 500
  session.timeout.ms: 90000
  heartbeat.interval.ms: 40000
  max.poll.interval.ms: 300000
  #producer config
  linger.ms: 0
  max.request.size: 1048576
  batch.size: 16384
  acks: "0"
  key.serializer: org.apache.kafka.common.serialization.StringSerializer
  value.serializer: org.apache.kafka.common.serialization.StringSerializer
  kafkaWriterThreadWaitTime: 1

bloomFilter:
  filter: true
  falsePositiveProbability: 0.0001
  expectedSize: 1000000
  name:
    - 5min-mdn-bloomFilter
    - 1hour-mdn-bloomFilter
    - 1day-mdn-bloomFilter
    - 1hour-CGI-bloomFilter
    - 1hour-domain-bloomFilter
  5min-mdn-bloomFilter: 
    fields: MSISDN
    size: 24
    timeGap: 5min
  1hour-mdn-bloomFilter: 
    fields: MSISDN
    size: 6
    timeGap: 1hour
  1day-mdn-bloomFilter: 
    fields: MSISDN
    size: 2
    timeGap: 1day
  1hour-CGI-bloomFilter:
    fields: ECGI
    size: 6
    timeGap: 1hour
  1hour-domain-bloomFilter:
    fields: Domain
    size: 6 
    timeGap: 1hour 
  
sourceFields:
  fields: 
      - MSISDN
      - ECGI
      - SGWIP
      - InputOctets
      - OutputOctets
      - Domain
      - TimeStamp
  delimiter: \|

couterList:
  #1小时内dpi的总数
  - dpi-1hour
  #1小时内用户数,去重后
  - huawei4g-userstat-1hour
  #5分钟内用户数,去重后
  - huawei4g-userstat-5min
  #1天用户数,去重后
  - huawei4g-userstat-1day
  #1小时内号码头用户数,去重后,如1331609
  - userstat-mdnprefix-1hour
  #1小时内短号码头用户数,去重后,如133
  - userstat-shortmdnprefix-1hour
  #1小时内号码头流量累积,单位为byte,如1331609
  - mdn-prefix-data-1hour
  #1小时内短号码头流量累积,单位为byte,如133
  - short-mdn-prefix-data-1hour
  #1天内号码头用户数,去重后,如1331609
  - userstat-mdnprefix-1day
  #1天内短号码头用户数,去重后,如133
  - userstat-shortmdnprefix-1day
  ##################todo::需要新开发############################
  #5分钟内用户累积流量,单位byte
  - user-data-5min
  #1小时内用户累积流量,单位byte
  - dpi-1hour-data
  #1小时内cgi数量,去重后
  - cgicount-1hour
  #一个小时内域名的总数,去重后
  - domaincount-1hour
  #1小时内域名访问的dpi数,三级域名,无需去重
  - domainstat-1hour
  
#derepeated mdn and mdn-prefix stat in 5 min
huawei4g-userstat-5min:
  type: com.gsta.bigdata.stream.counter.UserStatCounter
  flushes: elasticsearch
  flushTimeGapRatio: 1.1
  bloomFilter: 5min-mdn-bloomFilter
  timeGap: 5min
    
#derepeated mdn and mdn-prefix stat in 1 hour   
huawei4g-userstat-1hour:
  type: com.gsta.bigdata.stream.counter.UserStatCounter
  flushes: elasticsearch
  flushTimeGapRatio: 1.05
  bloomFilter: 1hour-mdn-bloomFilter
  timeGap: 1hour

#derepeated mdn and mdn-prefix stat in 1 day
huawei4g-userstat-1day:
  type: com.gsta.bigdata.stream.counter.UserStatCounter
  flushes: elasticsearch
  flushTimeGapRatio: 1.01
  bloomFilter: 1day-mdn-bloomFilter
  timeGap: 1day
    
userstat-mdnprefix-1hour:
  type: com.gsta.bigdata.stream.counter.MDNPrefixCounter
  flushes: elasticsearch
  flushTimeGapRatio: 1.05
  bloomFilter: 1hour-mdn-bloomFilter
  keyFields: mdnprefix  
  timeGap: 1hour

userstat-mdnprefix-1day:
  type: com.gsta.bigdata.stream.counter.MDNPrefixCounter
  flushes: elasticsearch
  flushTimeGapRatio: 1.01
  bloomFilter: 1day-mdn-bloomFilter
  keyFields: mdnprefix  
  timeGap: 1day

userstat-shortmdnprefix-1hour:
  type: com.gsta.bigdata.stream.counter.MDNPrefixCounter
  flushes: elasticsearch
  flushTimeGapRatio: 1.05
  bloomFilter: 1hour-mdn-bloomFilter
  keyFields: mdnprefix  
  shortmdnprefix: true 
  timeGap: 1hour

userstat-shortmdnprefix-1day:
  type: com.gsta.bigdata.stream.counter.MDNPrefixCounter
  flushes: elasticsearch
  flushTimeGapRatio: 1.01
  bloomFilter: 1day-mdn-bloomFilter
  keyFields: mdnprefix  
  shortmdnprefix: true 
  timeGap: 1day

#mdn prefix data count in 1 hour
mdn-prefix-data-1hour:
  type: com.gsta.bigdata.stream.counter.MDNPrefix1HourDataCounter
  flushes: elasticsearch
  flushTimeGapRatio: 1.05
  keyFields: mdnprefix
  
short-mdn-prefix-data-1hour:
  type: com.gsta.bigdata.stream.counter.MDNPrefix1HourDataCounter
  flushes: elasticsearch
  flushTimeGapRatio: 1.05
  keyFields: mdnprefix
  shortmdnprefix: true  
    
#dpi count in 1 hour
dpi-1hour:
  type: com.gsta.bigdata.stream.counter.DPI1HourCounter
  flushes: elasticsearch
  flushTimeGapRatio: 1.05

domainstat-1hour:
  type: com.gsta.bigdata.stream.counter.DomainStat1HourCounter
  flushes: elasticsearch
  flushTimeGapRatio: 1.05
  keyFields: Domain
#  outputKafkaTopic: tempDomain

mdn-day-data:
  type: com.gsta.bigdata.stream.counter.MDNDayDataCounter
  flushes: elasticsearch
  flushTimeGapRatio: 1.01
  continuousFlushes: mdnDayRedis
  #unit is second
  continuousFlushWaitTime: 120
  keyFields: MSISDN

###########NEW############
dpi-1hour-data:
  type: com.gsta.bigdata.stream.counter.DPIDataCounter
  flushes: elasticsearch
  flushTimeGapRatio: 1.05
  timeGap: 1hour
  
user-data-5min:
  type: com.gsta.bigdata.stream.counter.DPIDataCounter
  flushes: elasticsearch
  flushTimeGapRatio: 1.05
  timeGap: 5min
  
domainstat-1hour:
  type: com.gsta.bigdata.stream.counter.DomainStat1HourCounter
  flushes: elasticsearch
  flushTimeGapRatio: 1.05
  keyFields: Domain

cgicount-1hour:
  type: com.gsta.bigdata.stream.counter.CGI1HourCounter
  flushes: elasticsearch
  flushTimeGapRatio: 1.05
  bloomFilter: 1hour-CGI-bloomFilter

domaincount-1hour:
  type: com.gsta.bigdata.stream.counter.Domain1HourCounter
  flushes: elasticsearch
  flushTimeGapRatio: 1.05
  bloomFilter: 1hour-domain-bloomFilter

redis:
  host: XTH04-Sugoni840-9
  port: 6379
  #unit is second,604800 second = 7day
  keyExpire: 604800 
  maxTotal: 200
  maxIdle: 200
  minIdle: 8
  numTestsPerEvictionRun: 10
  timeBetweenEvictionRunsMillis: 30000
  minEvictableIdleTimeMillis: -1
  softMinEvictableIdleTimeMillis: 10000
  maxWaitMillis: 10000
  testOnBorrow: true
  testWhileIdle: true
  testOnReturn: true
  blockWhenExhausted: false

#Deprecated
elasticsearch:
  cluster.name: gd
  client.transport.sniff: true
  cluster.nodes:
      - XTH04-Sugoni840-8
      - XTH04-Sugoni840-9
      - XTH04-Sugoni840-10
      - XTH04-Sugoni840-11
      - XTH04-Sugoni840-12
  port: 9300
  index.name: 4gdpi
  batchRecord: 10000
  #unit is M
  batchSize: 5  
  numThread: 20
  flushTime: 5
